steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/api/Dockerfile
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/vedaai/api:latest
      - .
images:
  - asia-south1-docker.pkg.dev/$PROJECT_ID/vedaai/api:latest
timeout: 1200s
